//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurora_Item_Builder.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aurora_Item_Builder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strength,Dexterity,Constitution,Intelligence,Wisdom,Charisma ähnelt.
        /// </summary>
        internal static string AbilityList {
            get {
                return ResourceManager.GetString("AbilityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Armor,Medium Armor,Heavy Armor,Breastplate,Chain Shirt,Half Plate,Hide,Leather,Padded,Plate,Ring Mail,Scale Mail,Shields,Splint,Studded Leather ähnelt.
        /// </summary>
        internal static string ArmorProfs {
            get {
                return ResourceManager.GetString("ArmorProfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acid,Bludgeoning,Cold,Fire,Force,Lightning,Necrotic,Piercing,Poison,Psychic,Radiant,Slashing,Thunder ähnelt.
        /// </summary>
        internal static string DamageTypes {
            get {
                return ResourceManager.GetString("DamageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magic Item,Weapon,Weapon Property,Item ähnelt.
        /// </summary>
        internal static string ElementType {
            get {
                return ResourceManager.GetString("ElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dice Set,Dragonchess Set,Playing Card Set,Three Dragon Ante Set ähnelt.
        /// </summary>
        internal static string GamingSets {
            get {
                return ResourceManager.GetString("GamingSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abyssal,Common,Draconic,Dwarvish,Elvish,Giant,Gnomish,Goblin,Halfling,Infernal,Orc,Primordial,Sylvan,Undercommon ähnelt.
        /// </summary>
        internal static string LanguageList {
            get {
                return ResourceManager.GetString("LanguageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acrobatics,Animal Handling,Arcana,Athletics,Deception,History,Insight,Intimidation,Investigation,Medicine,Nature,Perception,Performance,Persuasion,Religion,Sleight of Hand,Stealth,Survival ähnelt.
        /// </summary>
        internal static string skillList {
            get {
                return ResourceManager.GetString("skillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bagpipes,Drum,Dulcimer,Flute,Lute,Lyre,Horn,Pan Flute,Shawm,Viol,Alchemists Supplies,Brewers Supplies,Calligraphers Supplies,Carpenters Tools,Cartographers Tools,Cobblers Tools,Cooks Utensils,Disguise Kit,Forgery Kit,Glassblowers Tools,Herbalism Kit,Jewelers Tools,Leatherworker Tools,Masons Tools,Navigators Tools,Painters Supplies,Poisoners Kit,Potters Tools,Smiths Tools,Thieves Tools,Tinkers Tools,Weavers Tools,Woodcarvers Tools ähnelt.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Darkvision,Blindsight,Truesight,Tremorsense,Mindsight ähnelt.
        /// </summary>
        internal static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battleaxe,Blowgun,Club,Crossbow Hand,Crossbow Heavy,Crossbow Light,Dagger,Dart,Flail,Glaive,Greataxe,Greatsword,Halberd,Handaxe,Javelin,Lance,Light Hammer,Longbow,Longsword,Mace,Martial Weapons,Maul,Morningstar,Net,Pike,Quarterstaff,Rapier,Scimitar,Sickle,Simple Melee Weapons,Simple Weapons,Sling,Shortbow,Shortsword,Spear,Trident,War Pick,Warhammer,Whip ähnelt.
        /// </summary>
        internal static string WeaponProfs {
            get {
                return ResourceManager.GetString("WeaponProfs", resourceCulture);
            }
        }
    }
}
